import type { Metadata } from 'next';
import './globals.css';
import { Providers } from '../provider/providers';
import { getServerSession } from 'next-auth';
import SessionProvider from '@components/SessionProvider';
import { Inter } from 'next/font/google';

export const metadata: Metadata = {
  title: `TWO - Today's WorkOut`,
  description: 'Generated by create next app',
};

const inter = Inter({
  subsets: ['latin'],
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang="en" className="dark">
      <body>
        <main className={`${inter.className} max-w-screen-sm mx-auto`}>
          <Providers>
            <SessionProvider session={session}>{children}</SessionProvider>
          </Providers>
        </main>
      </body>
    </html>
  );
}
