import type { Metadata } from 'next';
import './globals.css';
import { Providers } from '../provider/providers';
import { getServerSession } from 'next-auth';
import SessionProvider from '../components/SessionProvider';

export const metadata: Metadata = {
  title: 'MeTube',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang="en" className="light">
      <body>
        <Providers>
          <SessionProvider session={session}>{children}</SessionProvider>
        </Providers>
      </body>
    </html>
  );
}
