import type { Metadata } from 'next';
import Header from '../../components/Header';
import Side from '../../components/Side';

export const metadata: Metadata = {
  title: `TWO - Today's WorkOut`,
  description: 'Generated by create next app',
};

export default async function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <Header />
      <Side />
      {children}
    </div>
  );
}
